config/routes.rb
Rails.application.routes.draw do

  root 'links#index'
  devise_for :users
  resources :users, only: :show do
    # resources :links, only: :index
    get '/links', to: 'users#links'
  end
  resources :links, except: :index

  get "*path", to: "application#render_not_found"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord

  validates :url, presence: true, length: { minimum: 6 }
  validate :bad_word_validation

  self.per_page = 20

  def owner?(user)
    user_id == user.id
  end

  private

  def bad_word_validation
    unless BadWord.new(url).valid?
      errors.add(:url, I18n.t("activerecord.errors.models.link.attributes.url.bad_word"))
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    @links = Link.paginate(page: params[:page])
  end

  def show
    @link = Link.find(params[:id])
  end

  def new
    @link = Link.new
  end

  def create
    @link = current_user.links.new(links_params)
    if @link.save
      redirect_to link_path(@link.id)
    else
      render :new
    end
  end

  def edit
    @link = current_user.links.find(params[:id])
  end

  def update
    @link = current_user.links.find(params[:id])
    if @link.update(links_params)
      redirect_to link_path(@link.id)
    else
      render :edit
    end
  end

  def destroy
    @link = current_user.links.find(params[:id])
    @link.destroy
    redirect_to root_path
  end

private

  def links_params
    params.require(:link).permit(:url, :private)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    redirect_to user_links_path(params[:id])
  end

  def links
    @user = User.find(params[:user_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mylinks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<% if @link.errors.present? %>
<ul>
  <% @link.errors.each do |error, message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>
<%= form_for @link do |f| %>
  <div><%= f.text_field :url, placeholder: 'ссылка' %></div>
  <div>Приватная<%= f.check_box :private %></div>
  <%= f.submit %>
<% end %>

app/views/links/_link.html.erb
<div style="border-bottom: 1px solid black">
  <%= link.url %>
</div>

app/views/links/edit.html.erb
<h1>Редактировать ссылку</h1>
<%= render partial: 'form' %>

app/views/links/index.html.erb
<%= render @links %>
<%= will_paginate @links %>

app/views/links/new.html.erb
<h1>Создать ссылку</h1>
<%= render partial: 'form' %>

app/views/links/show.html.erb
<h1>Show link</h1>
<div><%= @link.url %></div>
<% if @link.owner?(current_user) %>
  <div>
    <%= link_to 'Редактировать', edit_link_path(@link.id) %>
    <%= link_to 'Destroy', link_path(@link.id), data: {confirm: 'Вы уверены?'}, method: :delete %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header style="border-bottom: 1px solid #333">
  <% if user_signed_in? %>
    <div><%= link_to 'Создать ссылку', new_link_path %></div>
    <div><%= current_user.email %></div>
    <div><%= link_to 'Выход', destroy_user_session_path, method: :delete %></div>
  <% else %>
    <div><%= link_to 'Войти', new_user_session_path %></div>
    <div><%= link_to 'Зарегистрироваться', new_user_registration_path %></div>
  <% end %>
</header>

app/views/users/links.html.erb
<div><%= @user.email %></div>

app/views/users/show.html.erb
<div><%= @user.email %></div>